import { createContext, useContext, useState, useEffect } from 'react';

const LangContext = createContext();

export function useLang() {
  return useContext(LangContext);
}

const translations = {
  hi: {
    appName: 'उधारी',
    appSub: 'स्मार्ट खाता ऐप',
    goodMorning: 'सुप्रभात 🌅',
    goodAfternoon: 'नमस्ते 🙏',
    goodEvening: 'शुभ संध्या 🌙',
    netBalance: 'कुल बैलेंस',
    toReceive: 'लेना है',
    toGive: 'देना है',
    allAccounts: 'सब के खाते',
    noCustomers: 'कोई ग्राहक नहीं',
    addFirstCustomer: 'नीचे + दबाओ, पहला ग्राहक जोड़ो!',
    search: 'नाम या फोन से खोजो...',
    credit: 'उन्होंने दिया',
    debit: 'तुमने दिया',
    toReceiveFrom: 'से लेना है',
    toGiveTo: 'को देना है',
    balanced: 'बराबर है',
    addTransaction: 'नया लेन-देन',
    addCustomer: 'नया ग्राहक',
    settings: 'सेटिंग्स',
    home: 'होम',
    reports: 'रिपोर्ट',
    logout: 'लॉगआउट',
    save: 'सेव करो',
    cancel: 'रद्द करो',
    delete: 'मिटाओ',
    edit: 'बदलो',
    confirm: 'पक्का',
    back: 'वापस',
    name: 'नाम',
    phone: 'फोन',
    amount: 'राशि',
    note: 'नोट',
    date: 'तारीख',
    dueDate: 'अंतिम तिथि',
    tag: 'टैग',
    interest: 'ब्याज',
    overdue: 'देर हो गई',
    vip: 'वीआईपी',
    regular: 'नियमित',
    defaulter: 'डिफॉल्टर',
    pinLock: 'पिन लॉक',
    language: 'भाषा',
    topDebtors: 'सबसे ज्यादा उधारी',
    analytics: 'विश्लेषण',
    exportPDF: 'PDF डाउनलोड',
    upiQR: 'UPI QR कोड',
    whatsapp: 'व्हाट्सऐप',
    sms: 'मैसेज',
    call: 'कॉल',
    undo: 'वापस लो',
    people: 'लोग',
    txHistory: 'लेन-देन इतिहास',
    noTx: 'कोई लेन-देन नहीं',
    addFirstTx: 'नीचे + दबाओ, पहली एंट्री करो!',
    partialPayment: 'आंशिक भुगतान',
    interestCalc: 'ब्याज कैलकुलेटर',
    monthlyReport: 'मासिक रिपोर्ट',
    weeklyReport: 'साप्ताहिक रिपोर्ट',
    receiveMsg: 'लेना रिकॉर्ड',
    giveMsg: 'देना रिकॉर्ड',
    deleteCustomer: 'ग्राहक मिटाओ',
    deleteCustomerConfirm: 'पक्का? सारा डेटा मिट जाएगा!',
    yes: 'हाँ, मिटाओ',
    no: 'नहीं',
    profileName: 'आपका नाम',
    dataSync: 'डेटा सिंक',
    live: '🟢 लाइव',
    accountType: 'खाता प्रकार',
    madeWith: 'बनाया प्यार से 💜 — उधारी ऐप',
    loginTitle: 'अपना उधार ट्रैक करो,\nटेंशन-फ्री रहो 💜',
    emailLogin: 'ईमेल',
    phoneLogin: 'फोन',
    login: 'लॉगिन',
    signup: 'खाता बनाओ',
    enterName: 'रामेश कुमार',
    enterEmail: 'आप@example.com',
    enterPassword: '••••••••',
    enterPhone: '+91XXXXXXXXXX',
    enterOTP: 'OTP डालो',
    sendOTP: 'OTP भेजो',
    verify: 'वेरीफाई करो',
    otpSentTo: 'OTP भेजा गया',
    goBack: 'वापस जाओ',
    loginBtn: 'लॉगिन करो',
    signupBtn: 'खाता बनाओ',
    pinSetup: 'PIN सेट करो',
    pinEnter: 'PIN डालो',
    pinConfirm: 'PIN दोबारा डालो',
    pinMismatch: 'PIN मेल नहीं खाती!',
    pinSet: 'PIN सेट हो गई!',
    pinRemove: 'PIN हटाओ',
    pinWrong: 'PIN गलत है',
    enablePin: 'PIN लॉक चालू करो',
    disablePin: 'PIN लॉक बंद करो',
    totalIn: 'कुल आया',
    totalOut: 'कुल गया',
    net: 'कुल',
    cashflow: 'कैश फ्लो',
    monthly: 'मासिक',
    weekly: 'साप्ताहिक',
    interestRate: 'ब्याज दर (% प्रति माह)',
    principal: 'मूल राशि',
    months: 'महीने',
    totalInterest: 'कुल ब्याज',
    totalAmount: 'कुल राशि',
    calculate: 'हिसाब लगाओ',
  },
  en: {
    appName: 'Udhaari',
    appSub: 'Smart Khata App',
    goodMorning: 'Good Morning 🌅',
    goodAfternoon: 'Good Afternoon 🙏',
    goodEvening: 'Good Evening 🌙',
    netBalance: 'Net Balance',
    toReceive: 'To Receive',
    toGive: 'To Give',
    allAccounts: 'All Accounts',
    noCustomers: 'No customers yet',
    addFirstCustomer: 'Tap + to add your first customer!',
    search: 'Search by name or phone...',
    credit: 'They Paid',
    debit: 'You Paid',
    toReceiveFrom: 'to receive from',
    toGiveTo: 'to give to',
    balanced: 'Settled up',
    addTransaction: 'New Transaction',
    addCustomer: 'New Customer',
    settings: 'Settings',
    home: 'Home',
    reports: 'Reports',
    logout: 'Logout',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    confirm: 'Confirm',
    back: 'Back',
    name: 'Name',
    phone: 'Phone',
    amount: 'Amount',
    note: 'Note',
    date: 'Date',
    dueDate: 'Due Date',
    tag: 'Tag',
    interest: 'Interest',
    overdue: 'Overdue',
    vip: 'VIP',
    regular: 'Regular',
    defaulter: 'Defaulter',
    pinLock: 'PIN Lock',
    language: 'Language',
    topDebtors: 'Top Debtors',
    analytics: 'Analytics',
    exportPDF: 'Export PDF',
    upiQR: 'UPI QR Code',
    whatsapp: 'WhatsApp',
    sms: 'SMS',
    call: 'Call',
    undo: 'Undo',
    people: 'people',
    txHistory: 'Transaction History',
    noTx: 'No transactions yet',
    addFirstTx: 'Tap + to add first entry!',
    partialPayment: 'Partial Payment',
    interestCalc: 'Interest Calculator',
    monthlyReport: 'Monthly Report',
    weeklyReport: 'Weekly Report',
    receiveMsg: 'Record Receive',
    giveMsg: 'Record Give',
    deleteCustomer: 'Delete Customer',
    deleteCustomerConfirm: 'Sure? All data will be deleted!',
    yes: 'Yes, Delete',
    no: 'No',
    profileName: 'Your Name',
    dataSync: 'Data Sync',
    live: '🟢 Live',
    accountType: 'Account Type',
    madeWith: 'Made with 💜 — Udhaari App',
    loginTitle: 'Track your credit,\nstress-free 💜',
    emailLogin: 'Email',
    phoneLogin: 'Phone',
    login: 'Login',
    signup: 'Sign Up',
    enterName: 'Ramesh Kumar',
    enterEmail: 'you@example.com',
    enterPassword: '••••••••',
    enterPhone: '+91XXXXXXXXXX',
    enterOTP: 'Enter OTP',
    sendOTP: 'Send OTP',
    verify: 'Verify',
    otpSentTo: 'OTP sent to',
    goBack: 'Go Back',
    loginBtn: 'Login',
    signupBtn: 'Create Account',
    pinSetup: 'Set PIN',
    pinEnter: 'Enter PIN',
    pinConfirm: 'Confirm PIN',
    pinMismatch: 'PINs do not match!',
    pinSet: 'PIN set successfully!',
    pinRemove: 'Remove PIN',
    pinWrong: 'Wrong PIN',
    enablePin: 'Enable PIN Lock',
    disablePin: 'Disable PIN Lock',
    totalIn: 'Total In',
    totalOut: 'Total Out',
    net: 'Net',
    cashflow: 'Cash Flow',
    monthly: 'Monthly',
    weekly: 'Weekly',
    interestRate: 'Interest Rate (% per month)',
    principal: 'Principal Amount',
    months: 'Months',
    totalInterest: 'Total Interest',
    totalAmount: 'Total Amount',
    calculate: 'Calculate',
  }
};

export function LangProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('udhaari_lang') || 'en');

  function toggleLang() {
    const newLang = lang === 'en' ? 'hi' : 'en';
    setLang(newLang);
    localStorage.setItem('udhaari_lang', newLang);
  }

  const t = translations[lang];

  return (
    <LangContext.Provider value={{ lang, toggleLang, t }}>
      {children}
    </LangContext.Provider>
  );
}
